### ISSUE TITLE
Use haskeline.

### ISSUE THREAD

**Issue by majecty** [kseo/scheme#12]
https://www.stackage.org/lts-5.14/package/haskeline-0.7.2.3

For support 
* Commandline history
* Short cuts like C-a, C-e

**Comment by noraesae** [comment]
Support for moving cursor with `←` and `→` would be nice as well.

**Comment by kseo** [comment]
@noraesae Haskeline supports moving the cursor with arrow keys!

**Comment by kseo** [comment]
#16 Landed
